"""Add SRS fields to Question model and image OCR support

Revision ID: b7cdcd5f9e6a
Revises: 442014fc3e44
Create Date: 2025-04-10 19:30:41.997113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7cdcd5f9e6a'
down_revision = '442014fc3e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('document_chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunk_document_id'), ['document_id'], unique=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('last_answered', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('times_answered', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('times_correct', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('next_review', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.alter_column('question_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_question_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_session_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_session_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_session_document_id'))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_user_id'))
        batch_op.drop_index(batch_op.f('ix_question_document_id'))
        batch_op.alter_column('question_type',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('content_hash')
        batch_op.drop_column('next_review')
        batch_op.drop_column('times_correct')
        batch_op.drop_column('times_answered')
        batch_op.drop_column('last_answered')
        batch_op.drop_column('difficulty')

    with op.batch_alter_table('document_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunk_document_id'))

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_user_id'))

    # ### end Alembic commands ###
