"""Add study_plans table

Revision ID: d78f7a0e0b5d
Revises: b7cdcd5f9e6a
Create Date: 2025-04-14 14:38:29.587792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd78f7a0e0b5d'
down_revision = 'b7cdcd5f9e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('weeks', sa.Text(), nullable=True),
    sa.Column('techniques', sa.Text(), nullable=True),
    sa.Column('milestones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_plan_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_plan_user_id'))

    op.drop_table('study_plan')
    # ### end Alembic commands ###
